version: 0.1
phases:
  pre_build:
    commands:
      - echo Install aws cli
      - apk add --no-cache aws-cli
      - echo Installing Dependencies
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      # Copy dist files to S3 bucket
      - aws s3 cp --recursive --acl public-read ./dist s3://${S3BucketName}/ 

      # Set cache-control headers to prevent Browser caching
      - >
        aws s3 cp --acl public-read 
        --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        ./dist/index.html s3://${S3BucketName}/